<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-DG0T5O6" name="testCases.TestModels_910" tests="20" failures="3" timestamp="2019-04-03T00:41:45 IST" time="14.805" errors="0">
  <testcase name="verify_ResponseCode_Manufacturer_910" time="0.871" classname="testCases.TestModels_910"/>
  <testcase name="verify_statusLine_Manufacturer_910" time="0.668" classname="testCases.TestModels_910"/>
  <testcase name="verify_ResponseHeader_ContntType_Manufacturer_910" time="0.554" classname="testCases.TestModels_910"/>
  <testcase name="verify_pageValues_Manufacturer_910" time="0.711" classname="testCases.TestModels_910"/>
  <testcase name="verify_TotalNumberOfModels_Manufacturer_910" time="0.880" classname="testCases.TestModels_910"/>
  <testcase name="verify_TotalNumberOfModelCodes_Manufacturer_910" time="0.645" classname="testCases.TestModels_910"/>
  <testcase name="verify_TotalNumberOfModelNames_Manufacturer_910" time="0.649" classname="testCases.TestModels_910"/>
  <testcase name="verify_ExpectedKeys_And_ActualKeys_Manufacturer_910" time="0.939" classname="testCases.TestModels_910"/>
  <testcase name="verify_ExpectedValues_And_ActualValues_Manufacturer_910" time="0.941" classname="testCases.TestModels_910"/>
  <testcase name="verify_ZeroModelCount_invalidManufacturerCode" time="0.648" classname="testCases.TestModels_910"/>
  <testcase name="verify_statusCode_invalid_Parameter_makers_Manufacturer_910" time="0.640" classname="testCases.TestModels_910"/>
  <testcase name="verify_statusLine_invalid_Parameter_makers_Manufacturer_910" time="0.618" classname="testCases.TestModels_910"/>
  <testcase name="verify_Error_Message_Exception_invalid_Parameter_makers_Manufacturer_910" time="0.711" classname="testCases.TestModels_910"/>
  <testcase name="verify_statusCode_invalid_Parameter_wa_kee_Manufacturer_910" time="0.939" classname="testCases.TestModels_910"/>
  <testcase name="verify_statusLine_invalid_Parameter_wa_kee_Manufacturer_910" time="0.924" classname="testCases.TestModels_910"/>
  <testcase name="verify_statusCode_invalid_wa_keyValue_Manufacturer_910" time="0.920" classname="testCases.TestModels_910"/>
  <testcase name="verify_statusLine_invalid_wa_keyValue_Manufacturer_910" time="0.630" classname="testCases.TestModels_910"/>
  <testcase name="verify_statusCode_invalid_Parameter_locals_Manufacturer_910" time="0.615" classname="testCases.TestModels_910">
    <failure type="java.lang.AssertionError" message="expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at testCases.TestModels_910.verify_statusCode_invalid_Parameter_locals_Manufacturer_910(TestModels_910.java:173)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_statusCode_invalid_Parameter_locals_Manufacturer_910 -->
  <testcase name="verify_statusCode_invalid_localValue_Manufacturer_910" time="0.674" classname="testCases.TestModels_910">
    <failure type="java.lang.AssertionError" message="expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at testCases.TestModels_910.verify_statusCode_invalid_localValue_Manufacturer_910(TestModels_910.java:181)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_statusCode_invalid_localValue_Manufacturer_910 -->
  <testcase name="verify_statusCode_By_Providing_ExtraParameter_Manufacturer_910" time="0.628" classname="testCases.TestModels_910">
    <failure type="java.lang.AssertionError" message="expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at testCases.TestModels_910.verify_statusCode_By_Providing_ExtraParameter_Manufacturer_910(TestModels_910.java:194)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_statusCode_By_Providing_ExtraParameter_Manufacturer_910 -->
</testsuite> <!-- testCases.TestModels_910 -->
