<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-DG0T5O6" name="testCases.TestBuiltDates_Alfa_145" tests="29" failures="3" timestamp="2019-04-03T00:41:45 IST" time="20.543" errors="1">
  <testcase name="verify_ResponseCode_Alfa_145" time="0.608" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_statusLine_Alfa_145" time="0.650" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_ResponseHeader_ContntType_Alfa_145" time="0.612" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_pageValues_Alfa_145" time="0.738" classname="testCases.TestBuiltDates_Alfa_145">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at io.restassured.path.json.JsonPath.getInt(JsonPath.java:244)
at testCases.TestBuiltDates_Alfa_145.verify_pageValues_Alfa_145(TestBuiltDates_Alfa_145.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- verify_pageValues_Alfa_145 -->
  <testcase name="verify_TotalNumberofBuiltDates_Alfa_145" time="0.933" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_TotalNumberOfBuiltDatesKeys_Alfa_145" time="0.936" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_TotalNumberOfBuiltDatesValues_Alfa_145" time="0.706" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_ExpectedKeys_And_ActualKeys_Alfa_145" time="0.846" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_ExpectedValues_And_ActualValues_Alfa_145" time="0.894" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_ZeroModelCount_invalidManufacturerCode" time="0.694" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_ZeroModelCount_invalidMaintypeCode" time="0.735" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_ZeroModelCount_invalidMaintypeCode_checkSpaces" time="0.860" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_ZeroModelCount_invalidMaintypeCode_checkCaseSensitive" time="0.662" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_statusCode_invalid_Parameter_makers_Alfa_145" time="0.593" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_statusLine_invalid_Parameter_makers_Alfa_145" time="0.655" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_Error_Message_Exception_invalid_Parameter_makers_Alfa_145" time="0.682" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_statusCode_invalid_Parameter_model_Alfa_145" time="0.924" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_statusLine_invalid_Parameter_model_Alfa_145" time="0.681" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_Error_Message_Exception_invalid_Parameter_model_Alfa_145" time="0.668" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_statusCode_invalid_Parameters_makers_And_model_Alfa_145" time="0.933" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_statusLine_invalid_Parameters_makers_And_model_Alfa_145" time="0.571" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_Error_Message_Exception_invalid_Parameters_makers_And_model_Alfa_145" time="0.546" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_statusCode_invalid_Parameter_wa_kee_Alfa_145" time="0.679" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_statusLine_invalid_Parameter_wa_kee_Alfa_145" time="0.686" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_statusCode_invalid_wa_keyValue_Alfa_145" time="0.624" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_statusLine_invalid_wa_keyValue_Alfa_145" time="0.605" classname="testCases.TestBuiltDates_Alfa_145"/>
  <testcase name="verify_statusCode_invalid_Parameter_locals_Alfa_145" time="0.625" classname="testCases.TestBuiltDates_Alfa_145">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at testCases.TestBuiltDates_Alfa_145.verify_statusCode_invalid_Parameter_locals_Alfa_145(TestBuiltDates_Alfa_145.java:257)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_statusCode_invalid_Parameter_locals_Alfa_145 -->
  <testcase name="verify_statusCode_invalid_localValue_Alfa_145" time="0.667" classname="testCases.TestBuiltDates_Alfa_145">
    <failure type="java.lang.AssertionError" message="expected [400] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at testCases.TestBuiltDates_Alfa_145.verify_statusCode_invalid_localValue_Alfa_145(TestBuiltDates_Alfa_145.java:265)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_statusCode_invalid_localValue_Alfa_145 -->
  <testcase name="verify_statusCode_By_Providing_ExtraParameter_Alfa_145" time="0.530" classname="testCases.TestBuiltDates_Alfa_145">
    <failure type="java.lang.AssertionError" message="expected [404] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [400]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at testCases.TestBuiltDates_Alfa_145.verify_statusCode_By_Providing_ExtraParameter_Alfa_145(TestBuiltDates_Alfa_145.java:282)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- verify_statusCode_By_Providing_ExtraParameter_Alfa_145 -->
</testsuite> <!-- testCases.TestBuiltDates_Alfa_145 -->
